# Always prefer bgr to hsv when red is a possible color
color:
  buoy:
    red:
      bgr_low: [0.0, 0.0, 30.6]
      bgr_high: [24.072, 25.398, 255.0]

    green:
      bgr_low: [0.0, 80.3505, 0.0]
      bgr_high: [255.0, 255.0, 24.4545]

    yellow:
      bgr_low: [0.0, 97.818, 24.4545]
      bgr_high: [41.922, 255.0, 255.0]

  channel_marker:
    hsv_low: [0.0, 0.0, 50.0]
    hsv_high: [83.3782, 255.0, 255.0]
